spring:
  datasource:
    url: jdbc:h2:mem:jpashop  # 메모리 모드로 변경
    username: sa
    password:
    driver-class-name: org.h2.Driver

  h2:
    console:
      enabled: true  # H2 콘솔 활성화 추가

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.H2Dialect  # 명시적으로 추가

logging.level:
  org.hibernate.SQL: debug